name: Deploy to GitHub Packages

on:
  push:
    tags:
      - '**'
  workflow_dispatch: # 👈 manual trigger from GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build & Deploy with Maven
        run: mvn --batch-mode clean deploy --settings .github/settings.xml
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }} # or GITHUB_TOKEN if using default GitHub token
