name: Bump version and tag release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version (e.g. 1.0.1)'
        required: true

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important: allows pushing tags

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update version in pom.xml
        run: |
          mvn versions:set -DnewVersion=${{ github.event.inputs.version }}
          mvn versions:commit

      - name: Commit and push version bump
        run: |
          git add pom.xml
          git commit -m "chore: bump version to ${{ github.event.inputs.version }}"
          git push origin HEAD

      - name: Create tag and push
        run: |
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}
